#!/usr/bin/env ruby
# frozen_string_literal: true

# archci-scan -- sync archlinux/packaging/state and report what is outstanding.
#
# The state repo has one file per package in <repo>-<arch>/<pkgbase>:
#   "<pkgbase> <version> <tag> <commit>"
# Nothing is queued here: archci-job claim asks archci-next for the next
# package just in time, comparing state/ with built/<repo>-<arch>/<pkgbase>.
require_relative '../lib/archci'

cfg = Archci.config
home = Archci.home
state = File.join(home, 'state')

File.open(File.join(home, 'lock', 'scan.lock'), File::RDWR | File::CREAT) do |lock|
  unless lock.flock(File::LOCK_EX | File::LOCK_NB)
    Archci.log 'another scan is running'
    exit 0
  end

  if File.directory?(File.join(state, '.git'))
    ok = system('git', '-C', state, 'pull', '-q', '--ff-only')
  else
    ok = system('git', 'clone', '-q', '--depth=1', cfg['ARCHCI_STATE_URL'], state)
  end
  abort 'archci-scan: could not sync the state repo' unless ok
end

outstanding = Archci.outstanding
updates = outstanding.count { |e| e['prio'] == 1 }
Archci.log "state synced: #{updates} update(s) and #{outstanding.size - updates} unbuilt package(s) outstanding"
